language: c
sudo: false
dist: xenial
branches:
  except:
    - appveyor
compiler:
 - gcc
addons:
 apt:
  packages:
   - pkg-config
   - bsdtar
   - libgraphite2-dev
   - libicu-dev
   - libreadline-dev
   - libssl-dev
   - libfreetype6-dev
   - libfontconfig1-dev
   - libpng-dev
   - libexpat1-dev
   - libipc-run-perl
   - libharfbuzz-dev
env:
  global:
   - LUAROCKS=2.4.2
   - GRAPHITE=true
   - COVERAGE=false
   - MAKEFLAGS="-j 4"
  matrix:
   - LUA=lua5.3 COVERAGE=true
   #- LUA=lua5.3 GRAPHITE=false
   # - LUA=lua5.2
   #- LUA=lua5.2 GRAPHITE=false
   # - LUA=lua5.1
   #- LUA=lua5.1 GRAPHITE=false
cache:
  directories:
  - $TRAVIS_BUILD_DIR/.fonts
  - $HOME/local
  # Cache object files etc. to speed up build
  - $TRAVIS_BUILD_DIR/libtexpdf
before_install:
 - source .travis/setenv_lua.sh
 - export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
 - export LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$HOME/local/lib:$LD_RUN_PATH
 - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
 # - if [ ! -f ~/.fonts/NotoSansMalayalam-Regular.ttf ]; then
 #      pushd ~/.fonts/ ;
 #      wget http://dealer.simon-cozens.org/~simon/tmp/silefonts.tar.gz ;
 #      tar xvf silefonts.tar.gz ;
 #      popd ;
 #   fi
 - export LUA_HOME_DIR=$TRAVIS_BUILD_DIR/install/lua
 - export LUA=~/.lua/lua
 - export LUA_INCLUDE=-I$LUA_HOME_DIR/include
 - export LD_LIBRARY_PATH=$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LIBRARY_PATH=$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$LUA_HOME_DIR/lib:$LD_RUN_PATH
 - export PATH=.travis:$PATH
install:
 - luarocks install lpeg
 - luarocks install lua-zlib
 - luarocks install luaexpat
 - luarocks install luafilesystem
 - luarocks install luasocket
 - luarocks install luasec
 - luarocks install lua_cliargs 2.3-3
 - luarocks install busted
 - luarocks install luacov 0.8-1
 - luarocks install luacov-coveralls
script:
 - fold_unless_fail 'Building' 'build' sh -c './bootstrap.sh && ./configure && make'
 - fold_unless_fail 'busted' 'busted'  busted --cpath="core/?.so" -m './lua-libraries/?.lua;./lua-libraries/?/init.lua' tests
 - fold_unless_fail 'Fetch resources used in tests' 'regression' make testprep
 - fold_unless_fail 'Run regression tests' 'regression' make test
 - fold_unless_fail 'Compile documentation and examples' 'compile_docs' make docs examples
 - fold_unless_fail 'Versions' 'versions' ./sile --debug=fonts,versions tests/bug-117.sil
after_success:
 - $COVERAGE && travis_wait make coverage
 - $COVERAGE && travis_wait luacov-coveralls -e lua.libraries
