trigger:
  - master
  - devel
jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
    - checkout: self
      submodules: true
    - script: |
        git config --global user.email "simon@simon-cozens.org"
        git config --global user.name "Azure Pipeline"

      displayName: Set git user name and email

    - script: cmake -G "Visual Studio 16 2019" -A x64 "-DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)\sile" -S "$(Build.SourcesDirectory)" -B "$(Build.BinariesDirectory)"
      displayName: Configure solution with CMake script

    - script: cmake --build "$(Build.BinariesDirectory)" --config Release
      displayName: Build solution

    - script: cmake --build "$(Build.BinariesDirectory)" --config Release --target Install
      displayName: Install solution

    - script: |
        "$(Build.SourcesDirectory)\.inno\build_installer.bat" "$(Build.SourcesDirectory)" "$(Build.ArtifactStagingDirectory)\sile" "$(Build.ArtifactStagingDirectory)\installer"

      displayName: Build installer

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)\sile
        artifactName: sile

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)\installer
        artifactName: installer